---

- name: Install the ssh package
  apt: name=ssh
  tags: ssh

- name: Configure sshd
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: restart ssh
  tags: ssh

- name: Add the ssh keys to user root
  authorized_key: user={{ item.user }} key="{{ lookup('file', item.path) }}" state="present"
  with_items: ssh.public_keys
  tags: ssh